### ISSUE TITLE
Bump pre-commit hooks automatically in [main]

### ISSUE THREAD

**Issue by kpatryk** [patryk-gpl/shell-utils#2]

**Comment by kpatryk** [comment]
Fixed by custom `pre-commit` workflow:

```
jobs:
  pre-commit:
    uses: kpatryk/workflows/.github/workflows/pre-commit.yml@v0.2.0
    with:
      os: ubuntu-latest
```
